spring:
  application:
    name: ecommerce-service
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: "gpt-4o-mini"
          temperature: 0
          max-tokens: 1000
          top-p: 1.0
          presence-penalty: 0.0
          frequency-penalty: 0.0
      embedding:
        options:
          model: "text-embedding-ada-002"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoint:
    health:
      show:
        details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server:
          requests: true
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html



logging:
  pattern:
    correlation: [ "${ spring.application.name: },%X{ traceId:- },%X{ spanId:- }" ]


